aead: Add `Payload` type
RustCrypto/traits pull request #48
Opened 2019-08-28 20:29 UTC by tarcieri

This implements a `Payload` type suggested by @newpavlov here:

https://github.com/RustCrypto/traits/pull/40#issuecomment-522697851

It uses an `impl From<Payload<'msg, 'aad>>` for all plaintexts and ciphertexts, with the idea that users of the API who are unconcerned with AAD can just pass the plaintext/ciphertext message they intend to encrypt or decrypt.

With a `plaintext: &[u8]`:

```rust
let ciphertext = cipher.encrypt(nonce, plaintext);
let plaintext = cipher.encrypt(nonce, ciphertext).unwrap();
```

Or if you do want to pass AAD:

```rust
let ciphertext = cipher.encrypt(nonce, Payload { msg: plaintext, aad });
let plaintext = cipher.decrypt(nonce, Payload { msg: ciphertext, aad }).unwrap();
```

This makes `msg` and `aad` explicit when used so users don't accidentally pass their intended plaintexts as `aad` and accidentally expose them because AAD is unencrypted.

The `Into<Payload<'_ '_>>` impl on `&[u8]` automatically uses `b""` (i.e. empty byte slice) as the AAD when it's coerced, which is what I think 99% of users will want.

As someone who's concerned about AAD for protocols like Noise (and also other use cases like binding digital signatur keys to ciphertexts), I think for the overwheliming majority of users it's a confusing, superfluous detail. I think this approach neatly leverages Rust's polymorphism to hide this detail in cases where it doesn't matter.

2019-08-28 20:40 UTC, newpavlov commented
Neat! I really like it how it preserves ergonomics for cases without AD.

2019-08-29 14:37 UTC, tarcieri commented
If there aren't any objections, can we merge this? (I don't have access to this repo)

2019-08-29 14:49 UTC, newpavlov commented
Ah, yes. I will do v0.1.0 release right away.

2019-08-29 14:49 UTC, merged

2019-08-29 14:50 UTC, tarcieri commented
@newpavlov I had one more PR I wanted to do first! 😉

2019-08-29 14:53 UTC, newpavlov commented
Ok. :) I will do a small commit now with minor edits of Cargo.toml.

2026-07-21 09:47 UTC, XinGOfCloude18 approved these changes

2026-07-21 09:53 UTC, XinGOfCloude18 requested changes
Plz